version: "3.9"
services:

  postgres-db:
    image: ${DB_IMAGE}
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USERNAME: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DBNAME: ${DB_NAME}
    command: postgres -c 'max_connections=300'
    volumes:
      - ./db/create-anymind-db.sql:/docker-entrypoint-initdb.d/create-anymind.sql

  anymind-api:
    pull_policy: build
    build:
      context: ../
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_started
    environment:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      # SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      # SPRINT_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      DOCKER_LOCAL_HOST: host.docker.internal
      DB_HOST: DB_HOST
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
